apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: default
spec:
  encryptedData:
    key: AgCKVRs7AOluXNucrlegEuG+LBOtFCbFg7m9ZPD8dwW57rN1fRXRkNo82KQ6xN6s34oVGJV+407C77wG0U1zsG07MdPU+I+mwWfhBMqWMVdPHTlCJNz6+cxd9HBM4vw/Q0IfkJAO2m8U2bmawb4SYGtSKkGxLhJQn+rP+yrajHh8qf5AZk1gMldxzDQJi7f91nkKgLpcqXL2NxdcTTaUYR6I3Sm15ZVXp8c+e36uqlj7X3zyJPqOpPI2rdCfl8P26InFhgL6QUioHDZVAvUsjb/ULHdsKrQHwNseBxdysBsMXyTwChDeEzCJHmPQoyIZ/kYmk9AUsLB1JhDuLrn7LFmS3UGmG9xyJdXJe5sjQlkvw44eO4/6GYuHOaYtFfQR9U/vv1Fph9fqSDvKwDv7tiTuboJCTRmwupHlXBLV1CWsaftRDhCPdSLMYxwFfcSWxp9rTNNudzyW4BdUJe8CGIKAr4sEjKsxdIS8MBftoBKK3V3b5INifS1WkNkBhE5ecgVuJtUyqbrd3RKS5TGRJDAxlNvxXfmP+IbEpOx+MFwkC7huOmJRpBDRh5P5xG+vcE7xsLOnMiVjZWQDkgSVT2fNbewLIBBdev/Nsa79bDXolOte1dIVRsN9+ZLL4Uf52A9NK5EzNrW3XtII2n2KjSvp47AAcgqIqU71T+8jTLjoE6xF/h+UpQ8TudInUI3z9nl6wXFkgmtFxVp2h2yy1MQtKyZ/8G8Kwl2eKK1TuGnqspS2i8kT303H
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: default

