---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: kube-system
spec:
  encryptedData:
    key: AgCyQd4jayXw9ajlh2Nh7ek7VKvkgMq7jKdKBxLhOl4JvUigsUZ6UkQpq05ij51qWU6q3n/1O8MQ3HrcOAWSyvOdYjS4En/T5Q71wfRMQHUXH+qIlmoFWSVBF9J15c8uAJoV9lhVsmBgUYbvySa0qEptC0/Jhx3sncRKAenZEF/uYf7jk1sqyVscK6JMKoSfu5+TsCe8WBWQ/NSrlV9Fv5+vcPzaFDTzaXRvH6HzwAfJdmRlRx1AApJlhS5wPJk/vHKp1fPwli8N2/7TmAipZvXeK1pgwlyCSjzpE1TzqPjAGnPSPwFs/X9OKCajF6ersnf5xcN0I+hGdcLOAydBB4bjyDtizLm7/H6G+5nGvReH9UMu5uwE3V75ozHbNoSk118RxjGRG2peOE+aUX7PiBovG9Qeoli/vX2MdqRtqj32FOhsAQ2Yh03hUEVvSS/8tXk4o+hBJ1tdP8ShliTnWS7Y1tr670yopPl+QKyjktqsoY2U1jKOWemt2FesQ9ZrtUGXMDpKuMUGUVHUE3sDXmPIANfC88b7ToXGrphCVcq+Dks2dqczQQxeN9hwOAktIUVESwcGiWXItCcu0mqKRsqz0Gm/omtbtOAf4gh6RioMY6MiAfGb88cXyhn1EC5HUhrC9JiVzSb90fO3+UVAMhsOYI1kTT2YMs2D1jWEk2z7tfIgkrCi32TTW7tB/1L+Z2ClRk71/kC3ujmZA9oDpWTZxmwRZYpoWjByy5sYQnrBzAGSD4FzfYoW
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: kube-system
    type: Opaque
