---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: kube-system
spec:
  encryptedData:
    key: AgAgxyXvuhj2Buy2cysWLCJdsN/U1WKjUTOtYfrp/xGkqjKjyFrIYQUGXqN3zRkX9T+sUnq0KDfibN+/brirTR4eNm40zb/j55rCEdlb9AYponc0XtVs75xdYVe2ypkTlTVlnZddb7hmKDM3frl5CDKMpknvJ52G+rjrf2aVAYcpZSyrShXrw+fyRw97AfV0R/V7hijKtsJQdXormxOK7zb6UAzfJIbi+cy0SU8+EUxgGs4MTR4ScfdWVteHBEYw+ZVCSPpz82Qeq+evN9/1EqGerzIW0K+2FkCKCmGsx4owftZEXMFcbVGfUWlY3c7xkz/7HYMzLeDgfqp4oLcmQ96fgL7Du/E5KMhfzjRU/rDFfReL4+NHBJkwFRlh1HknwS+fPs0WcPvJ3P9txQDbkZfbYIvs0Fie47hfr5ORS+7c8f7/G6cCeamNOl4PxTc1QBKfjI7fPnipAjH7T1e0AGe8iShdoobuU36GHNLhNpLCbHGzi2V7mh87VwtyyljjvQYWbp4ynZ4v0Fy+k0zCBZcsFUvo+/MkAgAJb3SnF2T2C7CBLAa7/u5QM0xRKtQeTfM6uVs1GnJqs+5kla8rWO+Za8KALA5xxq2M/3Mk29r1ULHlNqp4l9qZjkrjbkihcfab8NiEKrcaddxim/Z0Y0f2S9fcIIBoZH0uRnQAnFT0aMsQvuQZVIvVrE4oOCm8HJGg3QF8tYNNJ+/Emrvv+AhppSVdp+zuG3Wy0xWlQsbuETbuCeTFjTRD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: kube-system
    type: Opaque
