---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: kube-system
spec:
  encryptedData:
    key: AgCmcnpoSTHIHzh17oRsaT5KWFq+zE6GalwBDzX8hyCrX06MoU9LyMPcEJC02Gk733TTYWUSzoXFVEA4S/8tgDoCLaBYHPQFvT7yjxQiZ08EkjClsuDH6JNe6bmId6yZTnwB01JJtAI4PUU/q4F8xRIN71KrKFTLI9CJ//mVDSFCqL1l8u47ifGDAENHa3rDWz7Ss516uKbxr9fNU3/teTwvjIFcEa83S6XAbA1Jvd6M5eazI4mxY9gCEKdj4lTL4pan2PE35UBvv+oR8PdOuAoZUDP1YweXJyekYJThHczFV1rL0OrjuMHmlphCi/RGsj3LAAOqUxlgaz1CoY7MtV44PVW4bjmH4VRITbOzcxxqASSEqLZ8noJ5FW1zPsnNacGA6O6D+d6VelUpYM8AFJp2Vkv2iE7bioxf5NN397lFBIIR2Mt6PW4ck8dDbmHn0IUIeoH1l+iKswy5k0ISNvJFCHZ50UPC6IHpon2hYwBxdSZJT/Dv31UhM4UmHK8B9CZkA2y/QaCBjffj5pCPrboT09RxZvCRnAQpvXkSs4auX5tnOEC+/0G2algQIUQ3/jTZxIfkZZCUFQdvvAunVDgbs5GMWnD2nNiJu9GWMUFXmMtCIVN3AFNqTxluCxS5huFPmHyucpDFwndU3RnsYuuDBwJMYqmC+uxKphH/FgoibdUxtaDii33pMhTQe7zyg4olM/9mWbHwtO3pTAz9QMUoo37KzUyXrp04/ZtICg+xmgGKWMd7Dzqw
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: kube-system
    type: Opaque
