---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: kube-system
spec:
  encryptedData:
    key: AgA/n4aeFZjbxcJXiPfYodyfNmlY5TlqWFO2WYbBKnLoXCd5eXcjr+NIm9Ha+1hjLPdVm1mWgmkqkkAwuC8noVCGE3QXNYnxwtYLgcO4AbjfCccOJNo9wBkdNslZz5VFG+JyCc0ecUTmKErw9RzDoMha7TGkNWiD807DQx9XEmFqIY11sAJW4G48UYUD9b+WjtxVofJ9VEW6aOPQyLKH5Rqvi+ZSmhWnW1e4PTCCVKVyMRZfLy2vIsZUrB9khrmWkd+54LAKvHWZvgOCcKN0c/Mbl2dg8EYpe+jdC/k/wSLcCRuI2fbj48aLWxQVv/I4LwUL3gRNKqMT2aCXWm7FC0z4AJZXTQ9DEO4tvWczGCqoeGqqbIMAtWBq1h0OjSel7TLd1+clSqfXX+BLi+ooCoUpAyfwMQBaXe2KgxvKAy17M+U207+aXDT96fl7+kWGnVYc23+CIOgWRifzPaqkjAZ5gxCc0XfCvCmubjoT1XTjMsH/l4AMk1iYJh7BG/sED1zohvMs+ct3ksOJZ/CZGVhPMmaNACYvXYIeF3l4C6Zggd0hqHTelc1/uCXsB8SDmJX6VFl3sQwVSdy1FLj8KGvW6NM+JYDV5e7Hs5f3+7N89OEDbXXmcmHhyY0ioFl+3ySO7GDYZjnG0BZrfRe3nmNhHenlWvd6Ipr4lRHwp2MTsQj/paOePc1VUIl7U2bdtEuKuVNP1ITX/b5G1A8e3U72uHUADjC9S8t4P/UvgwR6SrSxTk7+aCHX
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: kube-system
    type: Opaque
