renovate:
  cronjob:
    schedule: "* * * * *"
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3

  renovate:
    existingConfigFile: renovate.json

  envFrom:
    - secretRef:
      name: env-renovate

