apiVersion: v2
name: cert-manager
description: Cert-manager
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: cert-manager
    version: v1.14.2
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled

