apiVersion: v2
name: cert-manager
description: Cert-manager
type: application
version: 1.0.0
dependencies:
  - name: cert-manager
    version: v1.18.1
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled

