apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: github-credentials
spec:
  encryptedData:
    sshPrivateKey: AgAMKlvyudq0tgXl8UJW4cnI2WW+kWHkS8NPfi4hBLfBMKHmM9X0WmyZHbXXAgSV3dIWR4KX7g05RE60Gt7eF7VyKCfldSdesdfrY8mfDfWSUfJg2uytWBEzt5gOjQFgPRy/Gkzhf/06B+10YMbWGbCfstnGEgIp5cRE000EBrkZZPx3uJogRDqWSZ73K12wamr6v8Uit2iSHs8Zh9CeoqygT4AFCWhw4tzIWJd94SHfKkmc71dHUnbTFS1tSr/Vbf/ZLeJhVU6BYvZlFFjS8U/OE2chFVTbDefUWynus58KAT9oB4OYtKJCvAoRiutlK4y/eOYTRrgl48X6pv5aJQNXW1uDAxjRMop786DNx4hjaiNuQannLbqC+30T434UDymDtcthKlyRof1EDgocc+WLDgzZfBMONWaVcm2tZqqd5T9dgliT3Dzoiq2ocZFWVXMx2SYXORFgq6HFdikMj4sLbw/xf/5ip0XA0pdt3pOG7lPDUES8gJHeCaRM13QVAVhZ81lFyqXz9SibN6/miWF7o22eJcpgyOM+YZ13YSSjRk7Bh7bCLggEKNf+8EEL31wBRPmUHiCgds7Wpjj0unwWD1aVL9h30oEetoXjtmrjzJbLKtFWAulYt/05Hl5vlq4wXyxOoqBMCewBpd7hIHVzEcasruds7L6PT1co4YvYT/BO4N/H0ZPYxl+/JhU81e11n7t7ZnXEJbqg1LWNmtUsQsrc/DVnxhwvjhjmNUydqexyeRpyqz/ZLMd9rD5qVwBlyT76qVo2VIb2+Qwr3mY/FqOI1joQ+Fh3AecLQVqWH6+CAkDXDXAxUN7nULhHbuH1wq8R8txenGksrk9ZyooSDruWMGEb/UyiaflysrVsNvPBVBo53Q33mA0sANj+sihHA/PPgAn/HGHa1TF3nupqVH76RxeVYJExfzYo/tT66DzTIdmQB4vZIDkpNstB5IIaY6TaX2VkRRk3KJ0xq6B6QwP2eC3lTn4vLfJVbOlziegGBRttXSIitEYJbyRwsrGJiXXLsmLuIc88odywiQEw6FT12XnD40s+kV0NYCejEnNW4mVmzu1WbIHbOu77+Y7pkZC1BVG0WqBYXurXCE6AWuT3YTlnFuJFMvZvwOiNuJTvW2q6oXhi8Fu5Nm5K8IcVmgsT2Q5DzQPENtCf56mWyTgYrw/BOrrGXfj8Wq/HBzRn5HdRiDm5ZjEduQaD+AGNNkCB0NzRgssM3COgpz0=
    url: AgCbNwYW/LAIkF50UnZ86DwS2JfF8qtlJ/MFItSao9AHmJNDjEcavK4QP6vfFkpVyMHV1QuB7AB/MpJ95n3ay10pqbbgGbJgpTei9FTwUwE6xz5V4nYT6uGhrelzhR54WdB9f7GrIpr9Vsv2rnWONpHNgzimlr4PATseUI+s1hJrYQ0Hd2ySkwPxna4p7/bXdiUqx/Whma/NT0dxbKKvTXDRzuwAZpQE8IMdeLq0yuKhFJipwlZyH1a5oKNPlnDVwRRc7xDUoWFotGcVrkEoAJY+PPFjFuezGIqOuRN71DFz2nJWYq9kE5lZbmp8k72d+p8h4CsZN6bCA1uVLApMXNos9B1XSMq1dTu4yjGoQw4yJIJzmjbQO/eLqjJ5roLUmu0NTfSoq3nQZRY2XCFQ7UZTttHPzJ1AI5FE3yC2eJfP5fmdBFMpmdtATb/NN1BHhhNUZhv9IMLImQhuqMFr0N8fROA8AEWIA3fMQNiWU6doBDRONhgX0NsG/XJ5CxjQvpIjxmy0kzm9W3zSeWWAKGBVSaPhxXJRWR70omBp4rG1kTrVfgTccbbP4yB7CVmZRX7AEDHX9bG8dpYF31ZKlO2M6Zue8I3nNfH6KKYQH6kTv0/A37MgIuW9FvdbB8GLJ6KdvzC/YTq1vCteG/ZaLBfZnVh55zDgvIgFqUFgLoB4upZ2EAHjl0HYhgrf2IqZU6PCJdqcEOgRZnfHTOWIMt+39UKz3LbM1/PDu/gblstSoUNsp7MTBg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: github-credentials
    type: Opaque

