---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-credentials
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgBecdG/PXGGWg7Mq9WdAKhMxN3WvSPMKp770byecZ6SxPJ7PKMKgmSI1fEy2LXU0tdASfuhruh+2Kjp2bNWZuAw68UVZlQYbpwDAZY4u7379C31CbTvHYJisGi9VBRr+7Hn7RLWy35Pud+ru2NoX3RDswTjBEAn6XnO+nUFsomin17VnpirtjeTniNROkG34FyUaRuP3XiVP+YdZJEnEWS7vPSqWUB7vBUzi5vSwYnvuNt4Nm4gBV0YBUE7CwxJSNC3tWshkqE98+9kX8FJk/kJglfwdRltOlbxjoSfre8r3IDFqMbbzpvq87I6+m/Vy4WDBpZ4N7WBg4TapgfE9h9Rl6k9prJE+edTCXDHsELGyL3KMy4FiIgUm2nvMcHlG77hEFn9rdmCnVA2u2ysoYXFl7KiwqiEJo3tMo+HupbWlztZoFftg57z8V2E7mI1up4IvMvm6QVHeTS89aXcn72Egt/XLoeVqBfzgsw4iSeZMU9azVtRx0WjJpiX3PWWU7rC05nnIFDXgrKxr+XKVBfUKLTcCO9OQje2CAVkFfHC7V04/Yuhk0HxMNlKNVd1KOOFtncvFrO5aacr4E+cqZOnkz78QofT0PRp1mloYtlwtpWK+knIrOnI65DSxA4mpYOw7fmeQ0hJ+FnoM4c5kZawX6hf50lmdtTfdpyKOrFhZAOfKrMFRrD9mw0OcyXIxUjnZnubroP7ClypyiICPf6cTEKk/7e6pHWDC8TtvMzCh1t0yp6xuXiUyGCf//323VAJAJXTqkp1haguUFeUaNamclDteTl1lNyPnxRvO8ihyFelsfpqqIDp91RkpZ7M9hNj1FtXm6iO1F6NJtEjjKLIZ6M+0wWwvh8SoHyDwHyGsHc0ShviU6EXk83ZokJFqgWGS1SWTngoRjG8uZcJSXpV5RN/LRX1ZohbSJXlEONGx2kBeyd/kpGGrtOuv7509A2aW0Bd7v+0XefOACVXkXOKrGMQSbDuK3c1y64tftnisXthmaO/zey9gegyyhi4OABSBb+sVl6auTcxRXVuecPTBZgEg1Jm+NtfQwl5qhNg1PJsTKDLunFNjmR8vfqtAj9IYSeTfAdVYKJt54iZVgHmlvOyL26Rtnk9ruTU1OXpenYEGovy7sNLfU9p26v9Y9n4WCZGB86k+gBjcV5XQ+ZWb30q9V3r1ekZnuevxFB3YRJ03/53/Uf5fwjcDyNZ9hLWIPazltfEscBZKNo6UZg=
    type: AgCwHXaI6LWWv0z3JON38MDQQihHKD4dT/AdtAl4REF6PNUnHcMlB96PvAT/Cdo3aw6WRiVIThZ7u/nny9taRIAYaEnopkJzWGFFutGz7MBH+jCkV3qktuANBFwQWCbIpPnH/q1t95gdjA2LUaFzBBGCCwmGMaLShrRD9zcPum9yX4i3o63dVS5YbQws49xGwJTm+BXFF0eZPncKjaSAqE2hm09VzfLBB/yeZaaEGnBNCK+8bQrUPjPJvyFkWc+huRcc2eb4HdNCAViBkAxlBzSVCvvpxKNlPfhzzQDc2WwgnfrUbtQaK1AwHH0UWrfzRSM+O5Lr08kkBpl7lm85xgl1MDe8ZZ1gK4nYG2+XreRFkgq+oIWrmpOQkSsgBz3DemkkTtBkpBwU0OFB6+sXEn6B2nVIMQL4LkzLpWxL8Wk56D9JXESeaNe4PgTGoxRgbPin/hC+0jkKF8LwNjySbE7o473qDdibyX8RofvUUBLb64MyFuuEWSPcT11VoUAGb3bX7ZN/7glGoBUQOUA/Su0xvuxYGjTagJnQBTmlhzKwULDJaAXt4vvdCcPY1AvrzM4GJzJCuIWiTvQGYZdh7jQsX+uo7jUiGAQbPqhu/cyEgYAursZwTZUtcwxWmxpqkvBBtQXTMjlHXEjL+rhvqJnGfqY6m6X8/LYq26xZx6gClnC8ofKrQlukni2D3g7EThzINww=
    url: AgCYEIDz/JnxQauIaJGNikM2WIYysTiXlgBeWtPa0b7Xj6s19+aNBzFmof4fvFvFOoWShPiKou/i0p1Dk3psvQbqFlUncWrpS7xjA7YHdD91VdtSQKC6QTZFsQA8Wmv8Jj7l4gKLjif6ZostUgyK+Eo2QOZ5shP8xiozVKzaJLs/h7elYuv7aCaAxSCko/fy08vgH0l5AUrygOT1RisGzt3cNlCaH+jiffnvg3qR5jTa1b+xA6Yv2vDM/z8ro7qR3SklyQFMiMr39nSShVHqGTvqooI/uClg47GHMeuoWq/RlvaWFFJizu+zN9a59WyiNNTboyFKEwxaWyrA17fodP4de2NI+17hVzM83b93JPgP4arv/UD7ymOAo7RAvQo419Dx+zGCMxxddbc4zJQRXCNzWXVTnJcsmxBw4BDd4EiD0y/r3wx6GpjwTsybYuIP/mTIZZs51fAwKh2kXIKQboi83HkAianXgAr58vnL/M89l1oV/9h++byn7UU2NmcnW2a+FeFHiB9Ep/FT9w2LsQDYSqeXldY8HGah0ST/+OiJ8g/JIHjbi5t1fR5H7YyWpmP+xRBGClGmxrVQJp+lKN86x22ME8KHCsOU62ddDLF3rMwIvrUlqaI/daTfEWgPvV+07wJNC6/TQ5T+9ufa1DU3r9ESftDdLD4C2ePhCupVdQ6N9zfJ3isMKxblAnvKmP9wgU0+kfciHFu/0Yck+4kfh3G0mh2O4ofz8jBbE+QLIh69zXBOhg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: github-credentials
      namespace: argocd
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgCtq3/CtvT3Ud59QV/ug3J8xSgF5lPMG6SVgXgLn6hC2QZKZDlM55Q3qNHvgaj3auyrYVRbYKFGtO3oXe9Yg8MteatymFvTa5cxDflKZOqmB+2QATInMZAB4zZxYEB84lz7SGT5xXfOoiuoHKQvwZYmUNdudETJ6UbGS7DfZXrTIi86TxIStaB+f8qnIEWDwG54OO65tGZjzbPDaXoKfH0UHUih9PKmlHQcyNxswwRjlTSowDbmAHq0/Bq3KqmOmhOSw9homFx/+9m6x7J1U8V5fhELtrRcVgiZ6xxakX3j41EMVDwpGnQrhraOM2De1hRbnsvvYXx8JI7PNr/b/DFlOlBs4fKq8UEEPb6Q2AlApIri+lHPlxz1flvgZ0VDkMh9PzAjIrSJwR+owFIKC0XgLW+5f4QoUFnzMYF3l94rdkyk95vD03ZKJvKiDvESJCyCgfAoSGdqoyKOt5M61Tb/ogA2/OXZBcvfM+lgt0t8THUga3vuZuEDbAjRNItm9IMp/HXKrhC85KkgF48gOhgp/MZtWwUkNI5sLfUaAWIhkryQwepqrbZD87axtnWJsyv4OMc9aZwxWhBfGRcYf0Mezf05ht4BnUvlqrBsOba7F7gckJPSn+VRe++FaRrWSCR1Q5b95FOh/3ryaA4Y7GaYdt3+QD3hhvCaLsUPmQOGBu1yOtmloznoBDS+fWFAf4SxTqEehKUbFDp9H4FWl+Gt9zeDWZU4wsnz+CJtJrkE0Q==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: keycloak
      namespace: argocd
