argo-cd:
  domain: argocd.dietz.dev

  server:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      extraTls:
        - hosts:
            - argocd.dietz.dev
          secretName: argocd-cert

  dex:
    enabled: false
