argo-cd:
  global:
    domain: argocd.dietz.dev

  server:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      extraTls:
        - hosts:
            - argocd.dietz.dev
          secretName: argocd-cert

  configs:
    admin.enabled: false
    cm:
      oidc.config: |
        name: SSO
        issuer: https://auth.dietz.dev/realms/dietz
        clientID: argocd
        clientSecret: $keycloak:clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
    rbac:
      policy.csv: |
        g, ArgoCDAdmins, role:admin

  dex:
    enabled: false
