metrics-server:
  apiService:
    insecureSkipTLSVerify: false
    caBundle: "-----BEGIN CERTIFICATE-----
MIIC/jCCAeagAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
cm5ldGVzMB4XDTIyMTAxMDIyMTAwNloXDTMyMTAwNzIyMTAwNlowFTETMBEGA1UE
AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKmJ
Wyv9/pFa2xwBJtJcrwD/UHexYIqJoCW5D2+vRduJrkqbXVohrfCZGQWJ+lTJBdJn
Ygcyn9SasJ8THrgUGBOxqOWPLzvRwq3TDtz7xC+hAHV8DbE3qEJPKNEQbHpcwLgb
5qdDNzLOpgGlEArwRaz/6FF9DtD51+aLqqel5xYkkZ77OfB71XpbuEOW8vl0HFa7
NVCiVZj5Dk3KeXq8y/ZvAT85Jh/rMMYaUbdLPOYF49t/EVaaNcJKQM5Wnrt9zgwo
MsLD0mmyJRoDKalHP9L4ldBMM0GY/9Z2ancUR9b3Oa4lDdHT6jhDwwOtuLpLjnIU
+tASDt+qOx5bP8XVMLECAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
/wQFMAMBAf8wHQYDVR0OBBYEFKFYFfF3qDAqIg/jm1l6LXebaXt1MBUGA1UdEQQO
MAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBAB+HDNgwYnQskJYndSr0
q7jswbxdEcAqXv/fY3HUVCP4l8VXAfYdgx47memxkUUKeFs8P4H02DXF8kH3Mbdx
kpPJJfxEbgyK1/00lMdAU3lK6ENKHlgDSIMmRSzL1Qs5pYZu6ig80hsMvpUEWyl6
KeVfEQPT8fQjm5lWqYk6EZWsxsCqKn2xEExn8QYtO/UxP2D42ISj/iruwDxR4tL/
SsKfTlPWDwE1LVKA0z/jYXHeHgCb/DT4n+xxjPGSYv80r5VBH2vSBdFa/TF+FXn4
iWOpTd12MyOAcIitoxk2+cRdvrBAH/Neajky+7G8K8Bh8GH57QUUZqP+ZXh1H75e
97Y=
-----END CERTIFICATE-----"

  defaultArgs:
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --kubelet-insecure-tls
    - --metric-resolution=15s
