apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cnpg
    name: in-cluster
  project: default
  source:
    path: component-config/cnpg
    repoURL: git@github.com:Pyrrha/home-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
