---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailu-data
spec:
  claimRef:
    name: mailu-storage
    namespace: mailu
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/mailu"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - srv-master

