apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii
spec:
  capacity:
   storage: 2Gi
  accessModes:
   - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /srv/firefly-iii
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - srv-master

