apiVersion: v2
name: firefly-iii-stack
version: 0.1.0
description: Firefly III stack
type: application
dependencies:
- name: firefly-iii-stack
  version: 0.8.0
  repository: https://firefly-iii.github.io/kubernetes/
home: https://github.com/firefly-iii/kubernetes
sources:
  - https://github.com/firefly-iii/kubernetes
maintainers:
  - name: morremeyer
    email: firefly-iii@mor.re
icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.github/assets/img/logo-small.png
