---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgAgPbzi4oZKPmzOI/YJ824Y7b0cBNUps6jasp9YhOzwDSxQ6W5kk7zBMraub5IpWjUPW9lPEMLenOBDlqGdLATjcviS4iuDddF+xkW+OzXnwLsx2buyQYKjTK0HnmZVDrmcXpjLnHQ4HsmlmckJv0Yys/Ujv73GO0HeSWfQWno2QtutzAZ4B6UF8Lt1KJQqgXRPid+HH+57QESNfCglkf8Nzc4fu0Yzxm+SE104+NrQ0DDEnVjjMDf37xA02AzYSGSpag2BzI2rL5KVtbosGcozNNwxAseVkCc+vA7gvRWav0TZ/i711L0CYqfTgQxGLcArsbzOU7r3A4AzUZoOw9D1vKgdKJFwHODVL6Fu46sByYJe9pqDZ4oZPBqjACNMF6gTVTT7LW1qlMkdsPsWG6/3Zi8lpaSFqy0OgBIFxv2Vx3jTJSvdFu8JZtDiBw+TWS8qyGgR4+pkfWltUiktascZGEOeGqFHPO/Bl2Hh2AjtgLaB3CD8nIIggysMQ62TWWBr/+FXqJwSX2PMpy57udzs6g2vDpTbS+yHKSltqnxHksceCkZvW81Ct/FqLxfa9HqfexJyJtoBLE5M+n5fg3QQIs8TWYLoTyVQG27ejk/pFOnbrs1r5C38wjCSGj9OoIfbk4mJYIcCe9iazaw2fz4IppExnbwajXLaGtg93TW7dIlWjdl1eN82eKEiLJg9LUxtGt5i1sor3rGxFjsiNo6e6dzaAA==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: database
    type: Opaque
