apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: database
    app.kubernetes.io/name: postgresql
  name: database-pvc
  namespace: database
spec:
  volumeName: database-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  volumeMode: Filesystem
