calcom-stack:
  postgresql:
    auth:
      username: unicorn_user
      password: magical_password
      database: calcom
    primary:
      persistence:
        storageClass: local-storage

  calcom:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: meet.dietz.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - secretName: meet-dietz-dev
        hosts:
          - meet.dietz.dev
