apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /srv/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - srv-master

