apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: minecraft
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 32565
