---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cluster-postgres-calcom
  namespace: database
spec:
  encryptedData:
    password: AgB28XA2+OZp23trbYRxEusm8SPsGu4FYRU5R+vcQbbtm/rSv7Vkt05Fvkm2wj5N3ly0zm5YLi6JAPnbn7s+IGTMIaulSVfJRkulOY5FojKPLkqSJqDOSMnF4Csysg4ZSbrsrcUo4qQDOUJAeQUBX8QNemA0tZkqA2uNHNlWn2M4W5fjH7B8EzcrgKaarsKUySkBkxC0+JNPun7EN3B4PRasHVtdaLGrPRX/gDZBkERKx/lXXPKJpPDPOEjPdKFxj/m2YsS9KiwFWVMnCHsJs7ekZZysF1S/dczsmlyoxfaPlM3B629gkDpx42QbhJNf8ODLUd9hThVSB3Jt3IB+YX45lOEwY9ypXe6BLdI+355hAH5+QZtY2yrBEsP0MgreyL6XovRJCw7gnznsMNkPqzkXjN3cQ5MM95ySXuAOCztIxjrXnXNhNvI1HViVcxzHjoOG957n3wN4v5v3FjnpzNpmO2mpcdMGsBfSu3Q5OcilyI4bBVWPZ2jY/Ma1QtfQkxVxi+WeLO9k3lWHNHeiG+RFhUxTV3rJ9xqcPcpcZeb2+/N/bq383JfDgWnO7jRxvVyYPErK879jBur1J89LJzimTNklix3FJQxcHgXB22tugRBmbhub3GoJ75igaiHXRtjvGiewYEZYuGbtf7dE7AL4/4BVYYFdJ8axNSm6ybciV4IUoWWs2YIRxG9bIYDLUmKlBWeprkASDbN5WlyCr3wibbuKlg==
    username: AgAs6dooWO1T526VmqXH5KfTNd3asFxmDxT4TTv8wYNgIigYJE9+IofGh8yu8wIm/av5QOlBE9NExkWNXoNsaxOflWGHYr2I3Pw9G9SrmH+Gul0mSTFGze/PebcSP+R2bLOSsg4O6OZLNuLw2HnYowqRmWiUaQcSRwBizwy2X06vEbf0kDEM7ueI/ZkYoAtiNHlCFsppZNvEfRqJgY7x6ndvH/assQE3O7sU78ipblu3GMPhjUtIPcJSDdsWisszdb2Y/KdHixj9VSGcxLe+pNt0FQmF1W7BRRz59PPfoKJSgsbHmCYoZQb7jqzBExUiv6gjz9xRTEf/k8Wqt5A7ketvOD508GbVKlh0brPaBLKEuH1hwK7z8CqAEei4kPEfJ/NzUCVz2XR/YwJdNRjTKpjLz2MrCWidF8bE/FTriE8OgvAjvUGfKD/R/0X3kHcMV828D8X5CHaBewL69FjO0dGVEItH/2A7+IE2WT2UicRh1Foqld8yCEapqO2hURHV6EAteZuklRuGzGSIp+bOTq344KJAt/9em/+IkIEXaU09MwxrmgxKN0XcN2cVztxEIdb2Xmu5erxufaO8qJo7mlWhr/2yl7HK++Ox/KI5aCwRI5Pdw0BJ0HgUiuSHanzR01yen6s3MLBiLZQj7oeTR/d1L9CwcyUzqTyk+LkbzKdApCgjfVBdsmkVu2I6DnF1+OnwAPuR+xc=
  template:
    metadata:
      name: cluster-postgres-calcom
      namespace: database
    type: Opaque
