keycloak:
  replicaCount: 1
  
  postgresql:
    enabled: false
  
  externalDatabase:
    existingSecret: keycloak-database-secret
    existingSecretHostKey: postgres-host
    existingSecretPortKey: postgres-port
    existingSecretUserKey: postgres-user
    existingSecretDatabaseKey: postgres-database
    existingSecretPasswordKey: postgres-password
  
  auth:
    adminUser: admin
    existingSecret: keycloak-admin-secret
    passwordSecretKey: admin-password

  proxyHeaders: "xforwarded"
  # extraEnvVars:
  #   - name: KC_HOSTNAME_DEBUG
  #     value: true

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: auth.dietz.dev
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    extraHosts:
      - name: codebusters.auth.dietz.dev
    extraTls:
      - hosts:
          - auth.dietz.dev
        secretName: keycloak-cert
      - hosts:
          - codebusters.auth.dietz.dev
        secretName: keycloak-codebusters-cert

  adminIngress:
    enabled: true
    ingressClassName: nginx
    hostname: auth-admin.dietz.dev
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    extraTls:
      - hosts:
          - auth-admin.dietz.dev
        secretName: keycloak-admin-cert

